"""
    Sat4Envi backend API

    The API documentation of the backend.  Access to definition group `public` is unrestricted. To access group `provider` you need extra permissions and group `private` isn't made available publicly.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.token_response import TokenResponse


class TestTokenResponse(unittest.TestCase):
    """TokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenResponse(self):
        """Test TokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
