"""
    Sat4Envi backend API

    The API documentation of the backend.  Access to definition group `public` is unrestricted. To access group `provider` you need extra permissions and group `private` isn't made available publicly.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest



class TestLoginRequest(unittest.TestCase):
    """LoginRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginRequest(self):
        """Test LoginRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginRequest()  # noqa: E501


if __name__ == '__main__':
    unittest.main()
