"""
    Sat4Envi backend API

    The API documentation of the backend.  Access to definition group `public` is unrestricted. To access group `provider` you need extra permissions and group `private` isn't made available publicly.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

from openapi_client.api.product_api import ProductApi  # noqa: E501


class TestProductApi(unittest.TestCase):
    """ProductApi unit test stubs"""

    def setUp(self):
        self.api = ProductApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_products(self):
        """Test case for get_products

        View a list of products  # noqa: E501
        """


if __name__ == '__main__':
    unittest.main()
