"""
    Sat4Envi backend API

    The API documentation of the backend.  Access to definition group `public` is unrestricted. To access group `provider` you need extra permissions and group `private` isn't made available publicly.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import py4envi
from py4envi.model.basic_product_category_response import BasicProductCategoryResponse


class TestBasicProductCategoryResponse(unittest.TestCase):
    """BasicProductCategoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasicProductCategoryResponse(self):
        """Test BasicProductCategoryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BasicProductCategoryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
