"""
    Sat4Envi backend API

    The API documentation of the backend.  Access to definition group `public` is unrestricted. To access group `provider` you need extra permissions and group `private` isn't made available publicly.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import py4envi
from py4envi.api.search_api import SearchApi  # noqa: E501


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_count(self):
        """Test case for get_count

        Get count of total scene results  # noqa: E501
        """
        pass

    def test_get_scenes(self):
        """Test case for get_scenes

        Search for scenes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
